"""
Structural Exporter - Export structural data for external analysis tools

Supports:
- ETABS (e2k format)
- SAP2000 (s2k format)
- CSV (generic format)
- JSON (for API integration)
"""

from typing import List, Dict, Any
from enum import Enum
from .structural_analyzer import StructuralElement, ElementType
from .revit_structural_extractor import StructuralModel
import json
import csv
import io


class ExportFormat(Enum):
    """Export formats"""
    ETABS = "etabs"
    SAP2000 = "sap2000"
    CSV = "csv"
    JSON = "json"


class StructuralExporter:
    """Export structural data to various formats"""

    def __init__(self, model: StructuralModel):
        """
        Initialize exporter

        Args:
            model: StructuralModel to export
        """
        self.model = model

    def export(self, format: ExportFormat) -> str:
        """
        Export model to specified format

        Args:
            format: Export format

        Returns:
            String representation of exported data
        """
        if format == ExportFormat.ETABS:
            return self._export_etabs()
        elif format == ExportFormat.SAP2000:
            return self._export_sap2000()
        elif format == ExportFormat.CSV:
            return self._export_csv()
        elif format == ExportFormat.JSON:
            return self._export_json()
        else:
            raise ValueError(f"Unsupported export format: {format}")

    def _export_etabs(self) -> str:
        """Export to ETABS e2k format"""
        lines = []

        # Header
        lines.append("$ ETABS Data File")
        lines.append("$ Generated by Vibe Building Structural Analyzer")
        lines.append("")

        # Units
        lines.append("UNITS FORCE LENGTH TEMP")
        lines.append("KN M CELSIUS")
        lines.append("")

        # Grids
        lines.append("GRID LINES")
        for i, level in enumerate(self.model.levels):
            elevation = level.get("elevation_m", 0)
            name = level.get("name", f"Level {i+1}")
            lines.append(f"  HORIZONTAL {name} {elevation}")
        lines.append("")

        # Materials
        lines.append("MATERIAL CONCRETE")
        lines.append("  CONCRETE C30")
        lines.append("  E 30000000")  # 30 GPa
        lines.append("  POISSON 0.2")
        lines.append("  DENSITY 25")  # 25 kN/m³
        lines.append("")

        # Frame sections (columns and beams)
        lines.append("FRAME SECTIONS")

        # Columns
        for column in self.model.columns:
            name = f"COL{int(column.width)}x{int(column.depth)}"
            width_m = column.width / 1000.0  # mm to m
            depth_m = column.depth / 1000.0
            lines.append(f"  {name} RECTANGULAR {width_m} {depth_m} CONCRETE")

        # Beams
        for beam in self.model.beams:
            name = f"BEAM{int(beam.width)}x{int(beam.depth)}"
            width_m = beam.width / 1000.0
            depth_m = beam.depth / 1000.0
            lines.append(f"  {name} RECTANGULAR {width_m} {depth_m} CONCRETE")
        lines.append("")

        # Frames (columns and beams)
        lines.append("FRAMES")

        # Columns
        for i, column in enumerate(self.model.columns):
            name = f"COL{int(column.width)}x{int(column.depth)}"
            lines.append(f"  COLUMN C{i+1} {name} {column.height}")

        # Beams
        for i, beam in enumerate(self.model.beams):
            name = f"BEAM{int(beam.width)}x{int(beam.depth)}"
            lines.append(f"  BEAM B{i+1} {name} {beam.length}")
        lines.append("")

        # Areas (slabs)
        lines.append("AREAS")
        for i, slab in enumerate(self.model.slabs):
            thickness_m = slab.depth / 1000.0
            lines.append(f"  SLAB S{i+1} {thickness_m} CONCRETE")
        lines.append("")

        # Load patterns
        lines.append("LOAD PATTERNS")
        lines.append("  DEAD DEAD 1")
        lines.append("  LIVE LIVE 1")
        lines.append("")

        return "\n".join(lines)

    def _export_sap2000(self) -> str:
        """Export to SAP2000 s2k format"""
        lines = []

        # Header
        lines.append("$ SAP2000 Data File")
        lines.append("$ Generated by Vibe Building Structural Analyzer")
        lines.append("")

        # Units
        lines.append("UNITS FORCE LENGTH TEMP")
        lines.append("KN M CELSIUS")
        lines.append("")

        # Materials
        lines.append("MATERIAL")
        lines.append("  CONCRETE C30 30000000 0.2 25")
        lines.append("")

        # Frame sections
        lines.append("FRAME SECTION")

        # Columns
        for column in self.model.columns:
            name = f"COL{int(column.width)}x{int(column.depth)}"
            width_m = column.width / 1000.0
            depth_m = column.depth / 1000.0
            lines.append(f"  {name} RECTANGULAR {width_m} {depth_m} C30")

        # Beams
        for beam in self.model.beams:
            name = f"BEAM{int(beam.width)}x{int(beam.depth)}"
            width_m = beam.width / 1000.0
            depth_m = beam.depth / 1000.0
            lines.append(f"  {name} RECTANGULAR {width_m} {depth_m} C30")
        lines.append("")

        # Joints (simplified: one joint per element)
        lines.append("JOINTS")
        joint_id = 1

        for column in self.model.columns:
            lines.append(f"  {joint_id} 0 0 0")
            joint_id += 1

        for beam in self.model.beams:
            lines.append(f"  {joint_id} 0 0 0")
            joint_id += 1
        lines.append("")

        # Frames
        lines.append("FRAMES")
        frame_id = 1

        for column in self.model.columns:
            name = f"COL{int(column.width)}x{int(column.depth)}"
            lines.append(f"  {frame_id} {frame_id} {frame_id+1} {name}")
            frame_id += 1

        for beam in self.model.beams:
            name = f"BEAM{int(beam.width)}x{int(beam.depth)}"
            lines.append(f"  {frame_id} {frame_id} {frame_id+1} {name}")
            frame_id += 1
        lines.append("")

        # Load patterns
        lines.append("LOAD PATTERNS")
        lines.append("  DEAD DEAD 1")
        lines.append("  LIVE LIVE 1")
        lines.append("")

        return "\n".join(lines)

    def _export_csv(self) -> str:
        """Export to CSV format"""
        output = io.StringIO()
        writer = csv.writer(output)

        # Elements table
        writer.writerow(["Type", "ID", "Length", "Width", "Depth", "Height", "Area", "Material", "Level"])
        writer.writerow(["", "", "m", "mm", "mm", "m", "sqm", "", ""])

        # Columns
        for column in self.model.columns:
            writer.writerow([
                "COLUMN",
                column.id,
                "",
                column.width,
                column.depth,
                column.height,
                "",
                column.material,
                column.level,
            ])

        # Beams
        for beam in self.model.beams:
            writer.writerow([
                "BEAM",
                beam.id,
                beam.length,
                beam.width,
                beam.depth,
                "",
                "",
                beam.material,
                beam.level,
            ])

        # Slabs
        for slab in self.model.slabs:
            writer.writerow([
                "SLAB",
                slab.id,
                slab.length,
                slab.width,
                slab.depth,
                "",
                slab.area,
                slab.material,
                slab.level,
            ])

        # Walls
        for wall in self.model.walls:
            writer.writerow([
                "WALL",
                wall.id,
                wall.length,
                "",
                wall.depth,
                wall.height,
                "",
                wall.material,
                wall.level,
            ])

        # Foundations
        for foundation in self.model.foundations:
            writer.writerow([
                "FOUNDATION",
                foundation.id,
                foundation.length,
                foundation.width,
                foundation.depth,
                "",
                foundation.area,
                foundation.material,
                "",
            ])

        return output.getvalue()

    def _export_json(self) -> str:
        """Export to JSON format"""
        data = {
            "metadata": {
                "generator": "Vibe Building Structural Analyzer",
                "version": "1.0",
                "format": "json",
            },
            "levels": self.model.levels,
            "elements": {
                "columns": [self._element_to_dict(col) for col in self.model.columns],
                "beams": [self._element_to_dict(beam) for beam in self.model.beams],
                "slabs": [self._element_to_dict(slab) for slab in self.model.slabs],
                "walls": [self._element_to_dict(wall) for wall in self.model.walls],
                "foundations": [self._element_to_dict(found) for found in self.model.foundations],
            },
            "summary": {
                "total_columns": len(self.model.columns),
                "total_beams": len(self.model.beams),
                "total_slabs": len(self.model.slabs),
                "total_walls": len(self.model.walls),
                "total_foundations": len(self.model.foundations),
            },
        }

        return json.dumps(data, indent=2, ensure_ascii=False)

    def _element_to_dict(self, element: StructuralElement) -> Dict[str, Any]:
        """Convert StructuralElement to dictionary"""
        return {
            "id": element.id,
            "type": element.element_type.value,
            "length": element.length,
            "width": element.width,
            "depth": element.depth,
            "height": element.height,
            "area": element.area,
            "volume": element.volume,
            "material": element.material,
            "level": element.level,
            "span": element.span,
            "loads": element.loads,
            "supports": element.supports,
            "supported_by": element.supported_by,
            "deflection": element.deflection,
            "deflection_ratio": element.deflection_ratio,
        }
